version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: demo_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 30

  mysql:
    image: mysql:8.4
    container_name: demo_mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 30

  wiremock:
    image: wiremock/wiremock:3.13.1
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--verbose"]

  ssh_server:
    image: lscr.io/linuxserver/openssh-server
    container_name: ssh_server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=test_user
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=pass
      - SUDO_ACCESS=false
    ports:
      - "2222:2222"
    volumes:
      - ./ssh/uploads:/home/test_user/uploads
      - ./ssh/downloads:/home/test_user/downloads

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10

  localstack:
    image: localstack/localstack
    container_name: localstack_main
    ports:
      - "4566-4599:4566-4599"
    environment:
      - TZ=Asia/Tokyo
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=s3,sqs,dynamodb
      - DYNAMODB_SHARE_DB=1 
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack/init-scripts:/etc/localstack/init/ready.d
